local translate = {}
------------- ../src/gui.c ----------------
translate["User definied simple pattern"] = "Trama simples pelo usuário"
------------- ../src/gui_attrib.c ----------------
translate["Error: Attribute must have a Tag"] = "Erro: Etiqueta precisa de um rótulo"
translate["ADD TAG"] = "ADD TAG"
translate["Add a Tag"] = "Add a Tag"
translate["Tag:"] = "Tag:"
translate["Value:"] = "Value:"
------------- ../src/gui_block.c ----------------
translate["Create a new block"] = "Create a new block"
translate["Enter insert point"] = "Enter insert point"
translate["Blocks Manager"] = "Blocks Manager"
translate["Attr"] = "Attr"
translate["Error: Don't remove Block in use"] = "Error: Don't remove Block in use"
translate["Remove Block"] = "Remove Block"
translate["Attributes"] = "Etiquetas"
translate["Edit Block"] = "Edit Block"
translate["New name:"] = "New name:"
translate["New description:"] = "New description:"
translate["Update"] = "Update"
translate["Text to Attributes"] = "Text to Etiquetas"
translate["Attrib. mark:"] = "Attrib. mark:"
translate["Hide mark:"] = "Hide mark:"
translate["Value mark:"] = "Value mark:"
translate["Default value:"] = "Default value:"
translate["Create block from:"] = "Create block from:"
translate["Interactive"] = "Interactive"
translate["Proceed"] = "Proceed"
translate["Path:"] = "Path:"
translate["Only reference"] = "Only reference"
translate["Full path"] = "Full path"
translate["Error: ivalid Block name"] = "Error: ivalid Block name"
translate["Error: exists Block with same name"] = "Error: exists Block with same name"
translate["NEW BLOCK"] = "NEW BLOCK"
translate["Error: in Block creation from file"] = "Error: in Block creation from file"
translate["Edit Block Attributes"] = "Edit Block Etiquetas"
------------- ../src/gui_circle.c ----------------
translate["CIRCLE"] = "CIRCLE"
translate["ARC"] = "ARC"
translate["Circular arc"] = "Circular arc"
translate["Place a circular arc"] = "Place a circular arc"
translate["Enter circle end point"] = "Enter circle end point"
------------- ../src/gui_config.c ----------------
translate["Internal standard pattern library"] = "Internal standard pattern library"
translate["Config"] = "Config"
translate["Preferences"] = "Preferences"
translate["3D"] = "3D"
translate["Preferences folder:"] = "Preferences folder:"
translate["Open folder"] = "Open folder"
translate["Config File:"] = "Config File:"
translate["Open file"] = "Open file"
translate["Reload config"] = "Reload config"
translate["The following window is used to visualize "] = "The following window is used to visualize "
translate["the raw parameters of the selected elements, according to "] = "the raw parameters of the selected elements, according to "
translate["the DXF specification. It is useful for advanced users to debug "] = "the DXF specification. It is useful for advanced users to debug "
translate["current file entities"] = "current file entities"
translate["Open Info Window"] = "Open Info Window"
translate[" or set all angles to 0"] = " or set all angles to 0"
translate["Top"] = "Top"
translate["Front"] = "Front"
translate["Right"] = "Right"
translate["Bottom"] = "Bottom"
translate["Rear"] = "Rear"
translate["Iso"] = "Iso"
------------- ../src/gui_dim.c ----------------
translate["Place a Linear Dim"] = "Place a Linear Dim"
translate["Fixed angle"] = "Fixed angle"
translate["Linear DIMENSION"] = "Linear DIMENSION"
translate["Place a Angular Dim"] = "Place a Angular Dim"
translate["Enter distance"] = "Enter distance"
translate["Fixed distance"] = "Fixed distance"
translate["Angular DIMENSION"] = "Angular DIMENSION"
translate["Place a Dimension:"] = "Place a Dimension:"
translate["Radial"] = "Radial"
translate["Diametric"] = "Diametric"
translate["Enter quadrant point"] = "Enter quadrant point"
translate["Enter oposite point"] = "Enter oposite point"
translate["Enter radius point"] = "Enter radius point"
translate["Enter location"] = "Enter location"
translate["Diametric DIMENSION"] = "Diametric DIMENSION"
translate["Radial DIMENSION"] = "Radial DIMENSION"
translate["Place a Ordinate Dim"] = "Place a Ordinate Dim"
translate["X"] = "X"
translate["Y"] = "Y"
translate["Enter start point"] = "Enter start point"
translate["Enter extension"] = "Enter extension"
translate["Next ordinate"] = "Next ordinate"
translate["Custom Text"] = "Custom Text"
translate["Ordinate DIMENSION"] = "Ordinate DIMENSION"
translate["Dimension Style Manager"] = "Dimension Style Manager"
translate["List of styles"] = "List of styles"
translate["Delete"] = "Delete"
translate["Error: Don't remove DIMSTYLE in use"] = "Error: Don't remove DIMSTYLE in use"
translate["Remove DIMSTYLE"] = "Remove DIMSTYLE"
translate["Selected parameters"] = "Selected parameters"
translate["Global Scale"] = "Global Scale"
translate["Meas. Factor"] = "Meas. Factor"
translate["Dec. places"] = "Dec. places"
translate["Annotation text:"] = "Annotation text:"
translate["Annotation text style:"] = "Annotation text style:"
translate["Terminator:"] = "Terminator:"
translate["Advanced"] = "Advanced"
translate["Term. size"] = "Term. size"
translate["Offset"] = "Offset"
translate["Extension"] = "Extension"
translate["Text size"] = "Text size"
translate["Text gap"] = "Text gap"
translate["Dim Style Name"] = "Dim Style Name"
translate["Error: DIMSTYLE already exists"] = "Error: DIMSTYLE already exists"
------------- ../src/gui_dupli.c ----------------
translate["DUPLI"] = "DUPLI"
translate["Duplicate a selection"] = "Duplicate a selection"
------------- ../src/gui_edit_attr.c ----------------
translate["Error: No attributes found"] = "Error: No Etiquetas found"
translate["Edit Attributes"] = "Edit Etiquetas"
translate["Select a Insert element"] = "Select a Insert element"
translate["Edit data"] = "Edit data"
translate["Hide"] = "Hide"
translate["Error: No spaces allowed in tags"] = "Error: No spaces allowed in tags"
translate["Edit Insert Attributes"] = "Edit Insert Etiquetas"
------------- ../src/gui_edit_text.c ----------------
translate["Edit a text"] = "Edit a text"
translate["Select a text element"] = "Select a text element"
translate["Enter a new text"] = "Enter a new text"
translate["Edit text"] = "Edit text"
------------- ../src/gui_ellip.c ----------------
translate["ELLIPSE"] = "ELLIPSE"
translate["Isometric Arc"] = "Isometric Arc"
translate["Left"] = "Left"
translate["Place a ellipse"] = "Place a ellipse"
translate["Enter center point"] = "Enter center point"
translate["Define major axis"] = "Define major axis"
translate["Define circle radius"] = "Define circle radius"
translate["Define minor axis"] = "Define minor axis"
translate["Enter arc start point"] = "Enter arc start point"
translate["Enter arc end point"] = "Enter arc end point"
------------- ../src/gui_explode.c ----------------
translate["EXPLODE"] = "EXPLODE"
translate["Explode elements"] = "Explode elements"
translate["Insert"] = "Insert"
translate["Attributes to text"] = "Etiquetas to text"
translate["Attributes to text:"] = "Etiquetas to text:"
translate["Value"] = "Value"
translate["Poly Line"] = "Poly Line"
translate["M Text"] = "M Text"
translate["Char"] = "Char"
translate["Raw"] = "Raw"
translate["Raw options"] = "Raw options"
translate["Poly"] = "Poly"
------------- ../src/gui_export.c ----------------
translate["HP-GL files (.plt)"] = "HP-GL files (.plt)"
translate["G-Code files (.nc)"] = "G-Code files (.nc)"
translate["Position and scale"] = "Position and scale"
translate["Driver specific"] = "Driver specific"
translate["Feed:"] = "Feed:"
translate["Init:"] = "Init:"
translate["End:"] = "End:"
translate["Move:"] = "Move:"
translate["Stroke:"] = "Stroke:"
translate["Export"] = "Export"
translate["Export: Created export output succesfully"] = "Export: Created export output succesfully"
translate["Export Error"] = "Export Error"
------------- ../src/gui_file.c ----------------
translate["Drawing files (.dxf)"] = "Drawing files (.dxf)"
translate["Text files (.txt)"] = "Text files (.txt)"
translate["Patterns files (.pat)"] = "Patterns files (.pat)"
translate["Line style files (.lin)"] = "Line style files (.lin)"
translate["PDF (.pdf)"] = "PDF (.pdf)"
translate["Up"] = "Up"
translate["Size"] = "Size"
translate["Date"] = "Date"
translate["Selected:"] = "Selected:"
translate["File explorer"] = "File explorer"
translate["Open Drawing"] = "Open Drawing"
translate["Recent:"] = "Recent:"
translate["Save Drawing"] = "Save Drawing"
translate["Current directory:"] = "Current directory:"
translate["File to Save on:"] = "File to Save on:"
translate["Existing File"] = "Existing File"
translate["Over write existing file?"] = "Over write existing file?"
------------- ../src/gui_find.c ----------------
translate["Find/Replace text"] = "Find/Replace text"
translate["Search:"] = "Search:"
translate["Tag"] = "Tag"
translate["Find Next"] = "Find Next"
translate["Replace:"] = "Replace:"
translate["Current"] = "Current"
translate["End of search"] = "End of search"
translate["Entire element"] = "Entire element"
translate["All"] = "All"
translate["REPLACE"] = "REPLACE"
translate["Total replaced: %d"] = "Total replaced: %d"
translate["No elements matched"] = "No elements matched"
------------- ../src/gui_hatch.c ----------------
translate["HATCH"] = "HATCH"
translate["Place a Hatch:"] = "Place a Hatch:"
translate["Points"] = "Points"
translate["Selection"] = "Selection"
translate["Associative"] = "Associative"
translate["User"] = "User"
translate["Solid"] = "Solid"
translate["Spacing"] = "Spacing"
translate["Confirm"] = "Confirm"
translate["Hatch Pattern"] = "Hatch Pattern"
translate["Family:"] = "Family:"
translate["Ref: 10 x 10 units"] = "Ref: 10 x 10 units"
translate["Choose"] = "Choose"
translate["Hatch Pattern Library (.pat)"] = "Hatch Pattern Library (.pat)"
translate["Add pattern family"] = "Add pattern family"
translate["File to Open:"] = "File to Open:"
------------- ../src/gui_image.c ----------------
translate["IMAGE"] = "IMAGE"
translate["Place Raster Image"] = "Place Raster Image"
translate["Attach"] = "Attach"
translate["Enter last corner"] = "Enter last corner"
------------- ../src/gui_info.c ----------------
translate["Info"] = "Info"
translate["Generate DB"] = "Generate DB"
translate["Cannot open database: %s\n"] = "Cannot open database: %s\n"
translate["Failed to fetch data: %s\n"] = "Failed to fetch data: %s\n"
translate["Failed to insert data: %s\n"] = "Failed to insert data: %s\n"
translate["Failed to put data\n"] = "Failed to put data\n"
translate["BLK:"] = "BLK:"
translate["ENTS:"] = "ENTS:"
------------- ../src/gui_insert.c ----------------
translate["Place a Insert"] = "Place a Insert"
translate["Choose Block:"] = "Choose Block:"
translate["Error: Block not allowed"] = "Error: Block not allowed"
translate["Error: Block not found"] = "Error: Block not found"
translate["Explore"] = "Explore"
translate["Enter place point"] = "Enter place point"
translate["Select Block"] = "Select Block"
translate["Block_names"] = "Block_names"
translate["Hidden"] = "Hidden"
translate["Select"] = "Select"
------------- ../src/gui_lay.c ----------------
translate["Layer Manager"] = "Layer Manager"
translate["C"] = "C"
translate["Line type"] = "Line type"
translate["Line weight"] = "Line weight"
translate["Error: Don't remove Layer in use"] = "Error: Don't remove Layer in use"
translate["Remove Layer"] = "Remove Layer"
translate["Layer Color"] = "Layer Color"
translate["Layer Name"] = "Layer Name"
translate["Error: Layer already exists"] = "Error: Layer already exists"
translate["Error: exists Layer with same name"] = "Error: exists Layer with same name"
------------- ../src/gui_line.c ----------------
translate["LINE"] = "LINE"
translate["Place a single line"] = "Place a single line"
------------- ../src/gui_ltype.c ----------------
translate["Line Types Manager"] = "Line Types Manager"
translate["Rename"] = "Rename"
translate["Error: Don't remove Line Type in use"] = "Error: Don't remove Line Type in use"
translate["Remove Line Type"] = "Remove Line Type"
translate["Global Scale Factor:"] = "Global Scale Factor:"
translate["Current Object Scale:"] = "Current Object Scale:"
translate["Line Type Name"] = "Line Type Name"
translate["Error: exists Line Type with same name"] = "Error: exists Line Type with same name"
translate["Add Line Type"] = "Add Line Type"
translate["Description:"] = "Description:"
translate["Apply Scale:"] = "Apply Scale:"
translate["From:"] = "From:"
translate["Copy"] = "Copy"
translate["Library"] = "Library"
translate["Default"] = "Default"
translate["Extra"] = "Extra"
translate["File"] = "File"
translate["Line Type Library (.lin)"] = "Line Type Library (.lin)"
translate["Load"] = "Load"
translate["Description"] = "Description"
translate["Preview:"] = "Preview:"
translate["Error: Select Source Line Type"] = "Error: Select Source Line Type"
translate["Error: Line Type already exists"] = "Error: Line Type already exists"
------------- ../src/gui_measure.c ----------------
translate["Measure Distance"] = "Measure Distance"
translate["Distance: %.9g"] = "Distance: %.9g"
translate["Angle: %.7g"] = "Angle: %.7g"
translate["Points: %d"] = "Points: %d"
translate["Total: %.9g"] = "Total: %.9g"
translate["Current:"] = "Current:"
translate["Last:"] = "Last:"
------------- ../src/gui_mirror.c ----------------
translate["MIRROR"] = "MIRROR"
translate["Mirror a selection"] = "Mirror a selection"
translate["Set the reflection line"] = "Set the reflection line"
translate["Enter second point"] = "Enter second point"
------------- ../src/gui_move.c ----------------
translate["MOVE"] = "MOVE"
translate["Move a selection"] = "Move a selection"
translate["Enter base point"] = "Enter base point"
------------- ../src/gui_mtext.c ----------------
translate["before = %d\n"] = "before = %d\n"
translate["after = %d\n"] = "after = %d\n"
translate["MTEXT"] = "MTEXT"
translate["Place an inteli text"] = "Place an inteli text"
translate["Text Height"] = "Text Height"
translate["Rect width"] = "Rect width"
translate["Edit inteli text"] = "Edit inteli text"
------------- ../src/gui_paste.c ----------------
translate["PASTE"] = "PASTE"
translate["Paste a selection"] = "Paste a selection"
translate["Enter destination point"] = "Enter destination point"
------------- ../src/gui_pline.c ----------------
translate["POLYLINE"] = "POLYLINE"
translate["Place a poly line"] = "Place a poly line"
translate["Bulge"] = "Bulge"
------------- ../src/gui_plugins.c ----------------
translate["Plugins"] = "Plugins"
------------- ../src/gui_point.c ----------------
translate["Place a single point"] = "Place a single point"
translate["POINT"] = "POINT"
------------- ../src/gui_print.c ----------------
translate["Portable Document Format (.pdf)"] = "Portable Document Format (.pdf)"
translate["Scalable Vector Graphics (.svg)"] = "Scalable Vector Graphics (.svg)"
translate["Image PNG (.png)"] = "Image PNG (.png)"
translate["Image JPG (.jpg)"] = "Image JPG (.jpg)"
translate["Image Bitmap (.bmp)"] = "Image Bitmap (.bmp)"
translate["Postscript (.ps)"] = "Postscript (.ps)"
translate["Page setup"] = "Page setup"
translate["px"] = "px"
translate["mm"] = "mm"
translate["inches"] = "inches"
translate["pixels"] = "pixels"
translate["Width:"] = "Width:"
translate["Scale & Position"] = "Scale & Position"
translate["Origin X:"] = "Origin X:"
translate["Origin Y:"] = "Origin Y:"
translate["Scale:"] = "Scale:"
translate["View"] = "View"
translate["Fit all"] = "Fit all"
translate["Centralize"] = "Centralize"
translate["Preview"] = "Preview"
translate["Color options:"] = "Color options:"
translate["Monochrome"] = "Monochrome"
translate["Dark"] = "Dark"
translate["Output format:"] = "Output format:"
translate["Destination:"] = "Destination:"
translate["Print: Created print output succesfully"] = "Print: Created print output succesfully"
translate["Print Error"] = "Print Error"
------------- ../src/gui_prop.c ----------------
translate["Edit Properties"] = "Edit Properties"
translate["Entity: %s"] = "Entity: %s"
translate["Layer:"] = "Layer:"
translate["Ltype:"] = "Ltype:"
translate["Color:"] = "Color:"
translate["LW:"] = "LW:"
translate["CHANGE PROPERTIES"] = "CHANGE PROPERTIES"
translate["Block:"] = "Block:"
translate["Scale X:"] = "Scale X:"
translate["Scale Y:"] = "Scale Y:"
translate["Scale Z:"] = "Scale Z:"
translate["Choose Color"] = "Choose Color"
------------- ../src/gui_rect.c ----------------
translate["RECT"] = "RECT"
translate["Place a rectangle"] = "Place a rectangle"
translate["Enter end point"] = "Enter end point"
------------- ../src/gui_rotate.c ----------------
translate["ROTATE"] = "ROTATE"
translate["Rotate a selection"] = "Rotate a selection"
translate["Confirm rotation"] = "Confirm rotation"
translate["Angle=%.4g°"] = "Angle=%.4g°"
------------- ../src/gui_scale.c ----------------
translate["SCALE"] = "SCALE"
translate["3 points"] = "3 points"
translate["Scale a selection"] = "Scale a selection"
translate["Keep Original"] = "Keep Original"
translate["Proportional"] = "Proportional"
translate["Factor"] = "Factor"
translate["X factor"] = "X factor"
translate["Y factor"] = "Y factor"
translate["Select/Add element"] = "Select/Add element"
translate["Enter pivot point"] = "Enter pivot point"
translate["First point"] = "First point"
translate["Confirm scale"] = "Confirm scale"
translate["End point"] = "End point"
translate["Factor=%.4g"] = "Factor=%.4g"
------------- ../src/gui_script.c ----------------
translate["db: Thread paused at: %s-line %d\n"] = "db: Thread paused at: %s-line %d\n"
translate["script timeout exceeded in %s, line %d, exec time %f s\n"] = "script timeout exceeded in %s, line %d, exec time %f s\n"
translate["cannot run script file: %s"] = "cannot run script file: %s"
translate["Auto check: no access to CadZinho enviroment"] = "Auto check: no access to CadZinho enviroment"
translate["Auto check: no access to CadZinho script object"] = "Auto check: no access to CadZinho script object"
translate["Script"] = "Script"
translate["Execute"] = "Execute"
translate["Breakpoints"] = "Breakpoints"
translate["Variables"] = "Variables"
translate["Script_controls"] = "Script_controls"
translate["Script file:"] = "Script file:"
translate["Lua Script (.lua)"] = "Lua Script (.lua)"
translate["Browse"] = "Browse"
translate["Source:"] = "Source:"
translate["Line:"] = "Line:"
translate["Add"] = "Add"
translate["Breakpoints:"] = "Breakpoints:"
translate["On/Off"] = "On/Off"
translate["Breaks"] = "Breaks"
translate["On"] = "On"
translate["Off"] = "Off"
translate["All Globals"] = "All Globals"
translate["All Locals"] = "All Locals"
translate["vars"] = "vars"
translate["Global:"] = "Global:"
translate["Global %s - %s\n"] = "Global %s - %s\n"
translate["Local:"] = "Local:"
translate["Print"] = "Print"
translate["Local %s - %s\n"] = "Local %s - %s\n"
translate["Output:"] = "Output:"
translate["Clear"] = "Clear"
translate["error: %s"] = "error: %s"
translate["Script %s"] = "Script %s"
------------- ../src/gui_select.c ----------------
translate["Select objects"] = "Select objects"
translate["Mode:"] = "Mode:"
translate["Toggle"] = "Toggle"
translate["+"] = "+"
translate["-"] = "-"
------------- ../src/gui_spline.c ----------------
translate["SPLINE"] = "SPLINE"
translate["Fit points"] = "Fit points"
translate["Place a spline by:"] = "Place a spline by:"
translate["Degree"] = "Degree"
translate["Closed"] = "Closed"
translate["Enter first point"] = "Enter first point"
translate["Enter next point"] = "Enter next point"
------------- ../src/gui_text.c ----------------
translate["TEXT"] = "TEXT"
translate["Place an text"] = "Place an text"
translate["Text:"] = "Text:"
translate["Height"] = "Height"
------------- ../src/gui_toolbox.c ----------------
translate["Toolbox"] = "Toolbox"
translate["Place"] = "Place"
translate["Dimension"] = "Dimension"
translate["Main"] = "Main"
translate["Layer: "] = "Layer: "
translate["ByB"] = "ByB"
translate["ByL"] = "ByL"
translate["Color: "] = "Color: "
translate["Line type: "] = "Line type: "
translate["Line weight: "] = "Line weight: "
translate["By Layer"] = "By Layer"
translate["By Block"] = "By Block"
translate["About"] = "About"
translate["CadZinho"] = "CadZinho"
translate["By Ezequiel Rabelo de Aguiar"] = "By Ezequiel Rabelo de Aguiar"
translate["CadZinho is licensed under the MIT License."] = "CadZinho is licensed under the MIT License."
translate["Build for: "] = "Build for: "
translate["Version: "] = "Version: "
translate["Discard changes"] = "Discard changes"
translate["Changes in drawing will be lost"] = "Changes in drawing will be lost"
translate["Discard"] = "Discard"
translate["attractors"] = "attractors"
translate["history"] = "history"
translate["%d of %d"] = "%d of %d"
------------- ../src/gui_tstyle.c ----------------
translate["Text Styles Manager"] = "Text Styles Manager"
translate["Name"] = "Name"
translate["Font"] = "Font"
translate["Subst"] = "Subst"
translate["Width"] = "Width"
translate["Fix H"] = "Fix H"
translate["Angle"] = "Angle"
translate["Flags"] = "Flags"
translate["Used"] = "Used"
translate["Create"] = "Create"
translate["Edit"] = "Edit"
translate["Remove"] = "Remove"
translate["Error: Don't remove Standard Style"] = "Error: Don't remove Standard Style"
translate["Error: Don't remove Style in use"] = "Error: Don't remove Style in use"
translate["Remove Style"] = "Remove Style"
translate["Fonts"] = "Fonts"
translate["Style Name"] = "Style Name"
translate["Error: Text Style already exists"] = "Error: Text Style already exists"
translate["Edit Text Style"] = "Edit Text Style"
translate["Name:"] = "Name:"
translate["Font:"] = "Font:"
translate["Width factor:"] = "Width factor:"
translate["Fixed height:"] = "Fixed height:"
translate["Oblique angle:"] = "Oblique angle:"
translate["Vertical"] = "Vertical"
translate["Backward"] = "Backward"
translate["Upside down"] = "Upside down"
translate["OK"] = "OK"
translate["Error: Duplicated Text Style"] = "Error: Duplicated Text Style"
translate["Error: STANDARD style can't be renamed"] = "Error: STANDARD style can't be renamed"
translate["Cancel"] = "Cancel"
translate["Manage Fonts"] = "Manage Fonts"
translate["Available Fonts"] = "Available Fonts"
translate["Shapes files (.shp)"] = "Shapes files (.shp)"
translate["Binary shapes file (.shx)"] = "Binary shapes file (.shx)"
translate["True type font file (.ttf)"] = "True type font file (.ttf)"
translate["Open font file (.otf)"] = "Open font file (.otf)"
translate["All files (*)"] = "All files (*)"
translate["Load font"] = "Load font"
------------- ../src/gui_txt_prop.c ----------------
translate["Edit Text Properties"] = "Edit Text Properties"
translate["Type:"] = "Type:"
translate["Style:"] = "Style:"
translate["Vert:"] = "Vert:"
translate["Horiz:"] = "Horiz:"
translate["Height:"] = "Height:"
translate["Angle:"] = "Angle:"
translate["Rec W:"] = "Rec W:"
translate["Modify"] = "Modify"
translate["CHANGE TEXT PROPERTIES"] = "CHANGE TEXT PROPERTIES"
translate["Pick"] = "Pick"
------------- ../src/gui_vertex.c ----------------
translate["Select a element"] = "Select a element"
translate["Click again to modify"] = "Click again to modify"
translate["Select Vertex"] = "Select Vertex"
translate["Confirm modification"] = "Confirm modification"
translate["Selected vertex:"] = "Selected vertex:"
translate["X:"] = "X:"
translate["Y:"] = "Y:"
translate["Z:"] = "Z:"
translate["Bulge:"] = "Bulge:"
translate["EDIT VERTEX"] = "EDIT VERTEX"
------------- ../src/gui_xy.c ----------------
translate["X="] = "X="
translate["len="] = "len="
translate["Y="] = "Y="
translate["ang="] = "ang="
translate["Polar"] = "Polar"
translate["Rectangular"] = "Rectangular"
translate["Relative"] = "Relative"
translate["Absolute"] = "Absolute"
------------- ../src/gui_zoom.c ----------------
translate["Zoom in rectangle"] = "Zoom in rectangle"
translate["Enter first corner"] = "Enter first corner"
translate["Enter zoom area"] = "Enter zoom area"

cadzinho.db_print(translate["User definied simple pattern"])